# Generated by Django 4.0.4 on 2022-06-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.DateField(null=True),
        ),
    ]
