# Generated by Django 4.0.4 on 2022-06-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapy", "0003_tehchnodom"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lalafo",
        ),
    ]
