# Generated by Django 4.0.4 on 2022-06-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapy", "0004_delete_lalafo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tehchnodom",
            options={"verbose_name": "Техно дом", "verbose_name_plural": "Техно дом"},
        ),
        migrations.AlterModelOptions(
            name="watchs",
            options={"verbose_name": "Часы", "verbose_name_plural": "Часы"},
        ),
    ]
