# Generated by Django 4.0.4 on 2022-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapy", "0005_alter_tehchnodom_options_alter_watchs_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchs",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
