# Generated by Django 4.0.4 on 2022-09-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0006_watchs_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehchnodom',
            name='price',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
