# Generated by Django 4.0.4 on 2022-09-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0008_alter_watchs_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehchnodom',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchs',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
