# Generated by Django 4.0.4 on 2022-06-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookshows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("img", models.ImageField(null=True, upload_to="")),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("author", models.CharField(max_length=100)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Fantazy", "Fantazy"),
                            ("Detective", "Detective"),
                            ("Humor", "Humor"),
                            ("Roman", "Roman"),
                            ("Adveture", "Adveture"),
                            ("Science_fiction", "Science_fiction"),
                        ],
                        max_length=100,
                    ),
                ),
                ("tom", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Shows_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ShowComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_date", models.DateField(auto_now_add=True)),
                ("update_date", models.DateField(auto_now=True)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_shows_comment",
                        to="bookshow.bookshows",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows_user",
                        to="bookshow.shows_user",
                    ),
                ),
            ],
        ),
    ]
