# Generated by Django 4.0.4 on 2022-05-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Fantazy', 'Fantazy'), ('Falklor', 'Falklor'), ('Detective', 'Detective'), ('Humor', 'Humor'), ('Roman', 'Roman'), ('Adveture', 'Adveture')], max_length=100)),
                ('tom', models.PositiveIntegerField()),
            ],
        ),
    ]
