# Generated by Django 4.0.4 on 2022-05-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookshow',
            new_name='Bookshows',
        ),
    ]
