# Generated by Django 4.0.4 on 2022-06-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookshows",
            options={"verbose_name": "Книга", "verbose_name_plural": "Книги"},
        ),
    ]
