# Generated by Django 4.0.4 on 2022-05-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshow', '0002_rename_bookshow_bookshows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshows',
            name='genre',
            field=models.CharField(choices=[('Fantazy', 'Fantazy'), ('Detective', 'Detective'), ('Humor', 'Humor'), ('Roman', 'Roman'), ('Adveture', 'Adveture'), ('Science_fiction', 'Science_fiction')], max_length=100),
        ),
        migrations.CreateModel(
            name='ShowComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_shows_comment', to='bookshow.bookshows')),
            ],
        ),
    ]
