# Generated by Django 4.0.4 on 2022-05-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshow', '0003_alter_bookshows_genre_showcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='showcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows_user', to='bookshow.shows_user'),
        ),
    ]
